language: python

python:
  - 3.6

install:
  - pip install deecubes

script:
  - deecubes -r ./raw -o ./docs --sync

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
